name: fixed_collections
description: Collections you can't modify
version: 0.1.0-beta
homepage: https://github.com/MelbourneDeveloper/fixed_collections

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^4.16.0
  lints: ^2.0.0
  test: ^1.16.0
